# This pre-commit file use for check code style before commit and also use for check code style in CI
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3

  # python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      # linter
      - id: ruff
        name: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # formatter
      - id: ruff-format
