name: Build and deploy the application to Koyeb

on:
  schedule:
    - cron: "45 7 * * *"
  push:
    branches:
      - "*"

jobs:
  deploy:
    concurrency:
      group: "${{ github.ref_name }}"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: "${{ secrets.KOYEB_EXAMPLES_APPS_TOKEN }}"

      - name: Build and deploy the application
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: fastapi-${{ github.ref_name }}
          service-env: "PORT=8080"
          service-ports: "8080:http"
          service-routes: "/:8080"
          skip-cache: true
